// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNefEbkOaM7wf2u4WL0VTNPRJ37j1Uvzg',
    appId: '1:91386520351:web:8479f4a44c5c9fbed6c62a',
    messagingSenderId: '91386520351',
    projectId: 'fitnam-app',
    authDomain: 'fitnam-app.firebaseapp.com',
    storageBucket: 'fitnam-app.appspot.com',
    measurementId: 'G-63NZ4DV9SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOJURxM3HETPI_fk8WiKDPKNdSFNjLBSI',
    appId: '1:91386520351:android:0769bfe7ad56630fd6c62a',
    messagingSenderId: '91386520351',
    projectId: 'fitnam-app',
    storageBucket: 'fitnam-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC77-yEEoD03ImrldR4mXz1v7FYkOepcfE',
    appId: '1:91386520351:ios:e129ee19b2e229b2d6c62a',
    messagingSenderId: '91386520351',
    projectId: 'fitnam-app',
    storageBucket: 'fitnam-app.appspot.com',
    iosClientId: '91386520351-g04hp0i5ll1arvmlva77m4hfl8esihlo.apps.googleusercontent.com',
    iosBundleId: 'com.mobilefactory.fitnam',
  );
}
