List<String> mottoData = [
  "Get a jump on your day",
  "Dare to be great",
  "Make yourself stronger than your excuses",
  "The only bad workout is no workout",
  "Your body hears everything that your mind says",
  "Love yourself enough to work harder",
  "Get In. Get Fit. Get on with Life",
  "Every day is a choice",
  "Push harder than yesterday if you want a different tomorrow",
  "Exercise your mind and body",
  "Make yourself proud",
  "Fitness is not a destination. It is a way of life",
  "Push yourself",
  "Start where you are. Use what you have. Do what you can",
  "Find a way or make one",
  "The Price of Excellence is discipline",
  "The hardest part is waking up",
  "Every day is a chance to become better",
  "Eat Sleep, Gym, and Repeat",
  "Hustle for the muscle",
  "Lift heavy today if you want strength tomorrow",
  "Fit does not quit",
  "Use your muscles or lose your muscles",
  "Lift like a worker and look like a boss",
  "Lift today, shape tomorrow",
  "No pain, No gain",
  "Less Fat, More Life",
  "The joy of Right Health",
  "Energize your Desire",
  "Get the body you want",
  "Look fit, feel fit",
  "Sore today, strong tomorrow",
  "Get the flat tummy you dream of",
  "Feel the difference",
  "Live longer and stronger",
  "Tame all terrors",
  "Fit is hit",
  "Move it and Lose it",
  "Fitness is 50% Mental and 50% Physical",
  "Sweat in the gym is the guarantee stamp for your health",
  "A healthy mind in a healthy body",
  "Fitness is an attitude",
  "Focus on what you lift",
  "Muscles will suit you",
  "This is your time to reset your lift",
  "The pain you suffer today is the sign of tomorrow's victory",
  "Look different, feel different",
  "Turn your fat into fit",
  "Fitness is the ultimate fashion",
  "Before your body, your mind comes to the gym",
  "Always something happening",
  "Be an Inspiration",
  "Enjoy life. Get fit",
  "Building confidence. Building fitness",
  "Celebrate Your Health",
  "Changing bodies, changing lives",
  "Everyone needs a balance in life",
  "Dare to be great",
  "Exercise until the body obeys",
  "Fit for life",
  "Get thin and win",
  "Fitter, healthier, happier",
  "Get a jump on your day!",
  "Anything you can conceive, you can achieve",
  "Improve yourself",
  "Bodies of stamina & strength",
  "In Pursuit of Good Health",
  "Forever fit, forever strong",
  "It's never too late to feel great",
  "Life's tough. Get fit",
  "Health & strength",
  "Fitness requires the shaping of the mind too",
  "Decide, Commit, Succeed",
  "The strength that shows",
  "It never gets easier. You just get stronger",
  "The quickest way to a top shape",
  "Where health, beauty, and fitness meet",
  "Losing never felt so good",
  "Nothing tastes as good as being fit feels",
  "Our goal is to help you reach yours",
  "Passionate experts energize lives",
  "Fat loss is a win",
  "Results, not promises",
  "Shape it up!",
  "Show off your guns",
  "Train like a Champion",
  "One life. Live well",
  "Success never comes to those who quit",
  "Take back your body",
  "Persist Until Something Happens",
  "Perspire to greatness",
  "Love your body",
  "Fitness for everyday people",
  "The quickest way to top shape",
  "Turn Fat into Fit!",
  "Use it or lose it",
  "We change lives",
  "Practice hard, play strong, pain is glory",
  "The fitness leader",
  "The only thing worth losing is weight",
  "Willpower knows no obstacles",
  "You can cry, just don't be a baby",
  "Your journey to a healthier life",
  "The best things in life make you sweaty",
  "You gotta be a beast",
  "Improvement matters",
  "Slow progress is better than no progress",
  "Get in the gym",
  "Find your focus",
  "Take a deep breath here",
  "Go beast mode",
  "Power, perseverance, and discipline",
  "You look good in muscles",
  "The gym is the best drug",
  "Become a gym rat",
  "Sweat the whole time",
  "Build a strong character",
  "Great for your body",
  "Sweating it out in the gym",
  "The best way to predict your future is to create it",
  "Where fitness comes naturally",
  "Results, not promises",
  "Forever fit, forever strong!",
  "Every day is a choice",
  "Decide, Commit, Succeed",
  "Do it because they said you couldn't",
  "Push harder today if you want a different tomorrow",
];
